//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int ID { get; set; }
        public string imageURL { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
    }
}
