//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketID { get; set; }
        public Nullable<int> ShowID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SeatID { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Shows Shows { get; set; }
        public virtual Users Users { get; set; }
    }
}
